source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/mappings.zsh

if [ -f ~/.sconfig/zsh/zshrc ]; then
	source ~/.sconfig/zsh/zshrc
fi

autopair-init

source ~/.config/zsh/prompt.zsh

source ~/.config/zsh/functions/cd_git_root.zsh

source ~/.config/zsh/functions/co.zsh
source ~/.config/zsh/functions/op.zsh
source ~/.config/zsh/functions/se.zsh
source ~/.config/zsh/tmux.zsh

